## Show bios version
alias bios='sudo dmidecode -s bios-version'
## Reboot in bios
alias rebios='sudo systemctl reboot -i --firmware-setup'

## Show kernel version
alias kernel='uname -r'
## Show OS infos
alias os='cat /etc/os-release'
## Show system infos
if [[ "$(cat /sys/devices/virtual/dmi/id/product_version 2>/dev/null)" == ThinkPad* ]]; then
	alias ff='fastfetch -l ~/.config/fastfetch/thinkpad-v.txt'
else
	alias ff='fastfetch'
fi

## Update the system
alias sysupdate='sys-update'

## Quick access to GitHub projects
alias gh='cd ~/Code/GitHub && ls'
## Using the 'docker' command for Podman
alias docker='podman'
